// German Master contract generator v1. Only the schema subset used here is supported.
import fs from "node:fs";
import path from "node:path";
const root = path.resolve(import.meta.dirname, "../..");
const defs = JSON.parse(
  fs.readFileSync(path.join(root, "contracts/v2/schema.json"), "utf8"),
).$defs;
const uuid =
  "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$";
const dt = "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$";
const allowed = new Set([
  "$ref",
  "oneOf",
  "discriminator",
  "type",
  "additionalProperties",
  "properties",
  "required",
  "const",
  "items",
  "minLength",
  "minimum",
  "maximum",
  "minItems",
  "maxItems",
  "uniqueItems",
  "enum",
  "format",
]);
function assertSubset(schema) {
  for (const key of Object.keys(schema))
    if (!allowed.has(key)) throw Error("Unsupported schema keyword: " + key);
  if (schema.type === "object") {
    if (
      schema.additionalProperties !== false ||
      JSON.stringify(schema.required) !==
        JSON.stringify(Object.keys(schema.properties))
    )
      throw Error("Generator requires closed objects with all fields required");
    Object.values(schema.properties).forEach(assertSubset);
  }
  if (schema.items) assertSubset(schema.items);
  schema.oneOf?.forEach(assertSubset);
  if (schema.format && !["uuid", "date-time"].includes(schema.format))
    throw Error("Unsupported format");
}
Object.values(defs).forEach(assertSubset);
const outputs = new Map();
const q = JSON.stringify;
const ref = (s) => s.$ref.split("/").at(-1);
function z(s) {
  if (s.$ref) return ref(s) + "Schema";
  if (s.oneOf)
    return `z.discriminatedUnion(${q(s.discriminator.propertyName)}, [${s.oneOf.map(z).join(", ")}])`;
  if (s.type === "object")
    return `z.strictObject({\n${Object.entries(s.properties)
      .map(([k, v]) => `  ${k}: ${z(v)},`)
      .join("\n")}\n})`;
  if ("const" in s) return `z.literal(${q(s.const)})`;
  let v =
    s.type === "string"
      ? "z.string()"
      : s.type === "integer"
        ? "z.number().int()"
        : s.type === "boolean"
          ? "z.boolean()"
          : s.type === "array"
            ? `z.array(${z(s.items)})`
            : null;
  if (!v) throw Error("Unsupported schema " + q(s));
  if (s.enum) v = `z.enum(${q(s.enum)})`;
  if (s.minLength !== undefined) v += `.min(${s.minLength})`;
  if (s.minimum !== undefined) v += `.min(${s.minimum})`;
  if (s.maximum !== undefined) v += `.max(${s.maximum})`;
  if (s.minItems !== undefined) v += `.min(${s.minItems})`;
  if (s.maxItems !== undefined) v += `.max(${s.maxItems})`;
  if (s.format === "uuid") v += `.regex(new RegExp(${q(uuid)}))`;
  if (s.format === "date-time")
    v += `.regex(new RegExp(${q(dt)})).refine(v => !Number.isNaN(Date.parse(v)) && new Date(v).toISOString().replace(".000Z", "Z") === v, "Invalid instant")`;
  if (s.uniqueItems)
    v += '.refine(v => new Set(v).size === v.length, "Duplicate items")';
  return v;
}
let ts =
  '// Generated by contracts/scripts/generate.mjs v1. Do not edit.\nimport { z } from "zod";\n';
for (const [n, s] of Object.entries(defs))
  ts += `export const ${n}Schema = ${z(s)};\nexport type ${n} = z.infer<typeof ${n}Schema>;\n`;
outputs.set("contracts/generated/typescript.ts", ts);
function kt(s) {
  if (s.$ref) return ref(s);
  return {
    string: "String",
    integer: "Int",
    boolean: "Boolean",
    array: `List<${s.items ? kt(s.items) : ""}>`,
  }[s.type];
}
function checks(k, s) {
  let c = [];
  if ("const" in s) c.push(`${k} == ${q(s.const)}`);
  if (s.minLength !== undefined) c.push(`${k}.length >= ${s.minLength}`);
  if (s.minimum !== undefined) c.push(`${k} >= ${s.minimum}`);
  if (s.maximum !== undefined) c.push(`${k} <= ${s.maximum}`);
  if (s.enum) c.push(`${k} in setOf(${s.enum.map(q).join(", ")})`);
  if (s.minItems !== undefined) c.push(`${k}.size >= ${s.minItems}`);
  if (s.maxItems !== undefined) c.push(`${k}.size <= ${s.maxItems}`);
  if (s.uniqueItems) c.push(`${k}.distinct().size == ${k}.size`);
  if (s.format === "uuid") c.push(`Regex(${q(uuid)}).matches(${k})`);
  if (s.format === "date-time") {
    c.push(`Regex(${q(dt)}).matches(${k})`);
    c.push(
      `runCatching { java.time.Instant.parse(${k}).toString() == ${k} }.getOrDefault(false)`,
    );
  }
  if (s.type === "array" && s.items.type === "string") {
    for (const x of checks("it", s.items)) c.push(`${k}.all { ${x} }`);
  }
  return c;
}
let kotlin =
  "// Generated by contracts/scripts/generate.mjs v1. Do not edit.\npackage com.germanverbmaster.android.foundation.contract\n\nimport kotlinx.serialization.Serializable\nimport kotlinx.serialization.SerialName\nimport kotlinx.serialization.json.*\n\n";
for (const [n, s] of Object.entries(defs)) {
  if (s.oneOf) {
    const first = defs[ref(s.oneOf[0])];
    const common = Object.entries(first.properties).filter(
      ([k, v]) =>
        k !== s.discriminator.propertyName &&
        s.oneOf.every((x) => q(defs[ref(x)].properties[k]) === q(v)),
    );
    kotlin += `@Serializable\n@OptIn(kotlinx.serialization.ExperimentalSerializationApi::class)\n@JsonClassDiscriminator(${q(s.discriminator.propertyName)})\nsealed class ${n} {\n${common.map(([k, v]) => `    abstract val ${k}: ${kt(v)}`).join("\n")}\n}\n\n`;
    continue;
  }
  const parent = Object.entries(defs).find(([, x]) =>
    x.oneOf?.some((y) => ref(y) === n),
  );
  const props = Object.entries(s.properties).filter(
    ([k]) => !(parent && k === parent[1].discriminator.propertyName),
  );
  const common = parent
    ? Object.keys(defs[ref(parent[1].oneOf[0])].properties).filter((k) =>
        parent[1].oneOf.every(
          (x) => q(defs[ref(x)].properties[k]) === q(s.properties[k]),
        ),
      )
    : [];
  kotlin += `@Serializable\n${parent ? `@SerialName(${q(s.properties[parent[1].discriminator.propertyName].const ?? s.properties[parent[1].discriminator.propertyName].enum?.[0])})\n` : ""}data class ${n}(\n${props.map(([k, v]) => `    ${common.includes(k) ? "override " : ""}val ${k}: ${kt(v)}`).join(",\n")}\n)${parent ? ` : ${parent[0]}()` : ""} {\n    init {\n${props.flatMap(([k, v]) => checks(k, v).map((c) => `        require(${c}) { ${q("Invalid " + n + "." + k)} }`)).join("\n")}\n    }\n}\n\n`;
}

function shape(e, s) {
  if (s.$ref) return `check${ref(s)}(${e})`;
  if (s.oneOf)
    return `run { val o = ${e} as? JsonObject ?: error("Expected object"); val tag=o[${q(s.discriminator.propertyName)}] as? JsonPrimitive ?: error("Missing discriminator"); require(tag.isString); when(tag.content) { ${s.oneOf.map((x) => `${q(defs[ref(x)].properties[s.discriminator.propertyName].const)} -> check${ref(x)}(${e})`).join("; ")}; else -> error("Unsupported discriminator") } }`;
  if (s.type === "object")
    return `run { val o = ${e} as? JsonObject ?: error("Expected object"); require(o.keys == setOf(${Object.keys(s.properties).map(q).join(", ")})); ${Object.entries(
      s.properties,
    )
      .map(([k, v]) => shape(`o.getValue(${q(k)})`, v))
      .join("; ")} }`;
  if (s.type === "array")
    return `run { val a = ${e} as? JsonArray ?: error("Expected array"); a.forEach { item -> ${shape("item", s.items)} } }`;
  const check =
    s.type === "string"
      ? "p.isString"
      : s.type === "integer"
        ? "!p.isString && p.intOrNull != null"
        : "!p.isString && p.booleanOrNull != null";
  return `run { val p = ${e} as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && ${check}) }`;
}
kotlin += "object ContractShape {\n";
for (const [n, s] of Object.entries(defs))
  kotlin += `    fun check${n}(element: JsonElement): Unit { ${shape("element", s)} }\n`;
kotlin += "}\n";
outputs.set(
  "apps/android/app/src/main/java/com/germanverbmaster/android/foundation/contract/Models.kt",
  kotlin,
);
for (const [file, body] of outputs) {
  const p = path.join(root, file);
  if (process.argv.includes("--check")) {
    if (!fs.existsSync(p) || fs.readFileSync(p, "utf8") !== body)
      throw Error("Generated drift: " + file);
  } else {
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, body);
  }
}
console.log(
  process.argv.includes("--check")
    ? "Contract generation is current."
    : "Generated TypeScript and Kotlin contracts.",
);
