export const privacyCopy = {
  en: { title:'Privacy and account', help:'Your download includes answers and preferences saved to your account. Sync work waiting on this device first if you want it included. Unsubmitted drafts remain here.', export:'Download my learning data', syncExport:'Sync my work and download data', saved:'Export downloaded. Keep it private; it contains your answers and preferences.', error:'Export failed. Saved work remains available. Retry explicitly.' },
  de: { title:'Datenschutz und Konto', help:'Dein Download enthält Antworten und Einstellungen aus deinem Konto. Synchronisiere zuerst ausstehende Übungen auf diesem Gerät, wenn du sie mitnehmen möchtest. Nicht abgeschickte Entwürfe bleiben hier.', export:'Meine Lerndaten herunterladen', syncExport:'Übungen synchronisieren und Daten herunterladen', saved:'Export heruntergeladen. Bewahre ihn vertraulich auf; er enthält deine Antworten und Einstellungen.', error:'Export fehlgeschlagen. Gespeicherte Daten bleiben erhalten. Versuche es erneut.' },
};
export const deletionCopy = {
  en: {title:'Delete local service learner data',help:'This fixture action deletes your learner data from the local service and this browser. It does not delete a host sign-in account. Export first if you want a copy.',begin:'Delete learner data…',confirm:'Delete all confirmed data and unsynced work for this learner? After the request is saved, practice and sync stop until deletion is confirmed.',delete:'Confirm deletion of learner data',cancel:'Keep my data',pending:'Deletion is saved. Practice and normal sync are blocked. Retry explicitly; your local work remains until confirmation.',completed:'Learner data deleted from the local service and this browser. This learner cannot resume practice.',confirmed:'The service confirmed deletion. This learner cannot resume practice. Finish local removal if needed.',cleanup:'Finish local removal',retry:'Retry saved deletion',error:'Deletion or local removal could not finish. The saved request is retained. Retry explicitly.',damaged:'Saved data could not be read, including the deletion record. It is preserved; no practice or upload is allowed.'},
  de: {title:'Lerndaten im lokalen Dienst löschen',help:'Diese Vorschauaktion löscht deine Lerndaten im lokalen Dienst und diesem Browser. Sie löscht kein Anmeldekonto. Exportiere zuerst eine Kopie, falls gewünscht.',begin:'Lerndaten löschen…',confirm:'Alle bestätigten Daten und nicht synchronisierten Vorgänge dieses Lerners löschen? Sobald die Anfrage gespeichert ist, bleiben Üben und Synchronisieren bis zur Bestätigung gesperrt.',delete:'Löschen der Lerndaten bestätigen',cancel:'Meine Daten behalten',pending:'Löschanfrage gespeichert. Üben und normale Synchronisierung sind gesperrt. Versuche es ausdrücklich erneut; lokale Daten bleiben bis zur Bestätigung erhalten.',completed:'Lerndaten im lokalen Dienst und diesem Browser gelöscht. Dieser Lerner kann nicht weiterüben.',confirmed:'Der Dienst hat die Löschung bestätigt. Dieser Lerner kann nicht weiterüben. Schließe bei Bedarf die lokale Entfernung ab.',cleanup:'Lokale Entfernung abschließen',retry:'Gespeicherte Löschung erneut senden',error:'Löschung oder lokale Entfernung nicht abgeschlossen. Die gespeicherte Anfrage bleibt erhalten. Versuche es ausdrücklich erneut.',damaged:'Die gespeicherte Löschanfrage ist nicht lesbar und bleibt erhalten. Üben und Hochladen sind gesperrt.'}
};
export const signoutCopy = {
  en:{title:'Sign out of local preview',help:'Sync saved requests first and keep unsubmitted drafts for this same learner, or explicitly remove this learner’s local work. Local removal does not delete server data. This fixture does not manage a host sign-in account.',sync:'Sync saved work and sign out',remove:'Remove local work and sign out…',confirm:'Remove this learner’s downloads, drafts and unsynced work from this browser?',confirmRemove:'Confirm local removal and sign out',cancel:'Keep my local work',signedOut:'Local learner access is paused. No practice or normal sync is allowed. Retained work belongs only to this learner.',resume:'Resume the same local fixture learner',retry:'Finish saved sign-out',error:'Sign-out could not finish. Sync failure keeps your work. A saved removal can be retried explicitly.'},
  de:{title:'Aus lokaler Vorschau abmelden',help:'Synchronisiere zuerst gespeicherte Anfragen und behalte nicht abgegebene Entwürfe für denselben Lerner, oder entferne ausdrücklich seine lokalen Daten. Lokale Entfernung löscht keine Serverdaten. Diese Vorschau verwaltet kein Anmeldekonto.',sync:'Synchronisieren und abmelden',remove:'Lokale Daten entfernen und abmelden…',confirm:'Downloads, Entwürfe und nicht synchronisierte Vorgänge dieses Lerners aus diesem Browser entfernen?',confirmRemove:'Lokale Entfernung und Abmelden bestätigen',cancel:'Meine lokalen Daten behalten',signedOut:'Lokaler Lernzugriff pausiert. Üben und normale Synchronisierung sind gesperrt. Behaltene Daten gehören nur zu diesem Lerner.',resume:'Denselben lokalen Beispiel-Lerner fortsetzen',retry:'Gespeichertes Abmelden abschließen',error:'Abmelden nicht abgeschlossen. Bei Synchronisierungsfehlern bleiben die Daten erhalten. Eine gespeicherte Entfernung kann ausdrücklich erneut versucht werden.'}
};
export const accountSignoutCopy = {
  en: {...signoutCopy.en,title:'Sign out',help:'Choose whether to sync saved practice or remove it from this device before signing out. Removing local work does not delete progress already saved to your account.',resume:'Continue after signing in to this account'},
  de: {...signoutCopy.de,title:'Abmelden',help:'Du kannst deine gespeicherten Übungen vor dem Abmelden synchronisieren oder die Daten auf diesem Gerät löschen. Bereits im Konto gespeicherter Lernstand bleibt erhalten.',resume:'Nach Anmeldung bei diesem Konto fortsetzen'},
};
