// Original controlled B2 drafts. Do not regenerate over editorial corrections.
import { writeFileSync, existsSync } from 'node:fs';
const destination = new URL('./b2-basics.json', import.meta.url);
if (existsSync(destination)) throw Error('Draft exists; edit it in place to preserve reviewer corrections.');
const text = (en, de) => ({ en, de });
const id = n => `40000000-0000-4000-8000-${String(n).padStart(12, '0')}`;
const targets = [];
function add(en, de, category, hint, explanation, examples) {
  const n = targets.length;
  targets.push({ id:id(n), title:text(en,de), objective:en, category, level:'B2',
    provenance:'Original Codex-authored controlled examples, 7 October 2026; AI editorial assistance, not independent German review. No legacy sentences imported.',
    review:{status:'pending',reviewer:null,date:null,notes:'',reviewedHash:null},
    variants:examples.map(([prompt,answer],v)=>({variantKey:`b2-${n}-${v}`,contextKey:`b2-context-${n}-${v}`,transferKey:v?`b2-transfer-${n}`:null,
      exercise:{schemaVersion:1,id:id(1000+n*2+v),revision:1,targetId:id(n),type:'cloze',prompt,
        slots:[{id:'form',label:'Form'}], hint,
        instruction:text('Complete only the gap, using the expression or form specified in parentheses.','Ergänze nur die Lücke mit dem Ausdruck oder der Form in Klammern.')},
      rubric:{normalizationVersion:'de-nfc-trim-v1',acceptedAnswers:(Array.isArray(answer)?answer:[answer]).map(a=>({type:'cloze',values:[{slotId:'form',text:a}]})),explanation},
      ambiguityNotes:'The parenthetical cue specifies the required lemma or construction. Evaluate that requested form, not arbitrary paraphrases. Independent level/naturalness/alternative-answer review pending.'}))});
}
add('Passive: present tense','Passiv im Präsens','passive',text('Use werden plus the past participle.','Verwende werden und das Partizip II.'),text('The present passive uses a present form of werden and the past participle: wird geprüft / wird bearbeitet.','Das Vorgangspassiv im Präsens besteht aus werden und dem Partizip II: wird geprüft / wird bearbeitet.'),[
 ['Der Antrag ___ von der Behörde geprüft. (werden, Präsens)','wird'],['Die Rechnung ___ heute bearbeitet. (werden, Präsens)','wird']]);
add('Passive: past tense','Passiv im Präteritum','passive',text('Put werden in the past tense.','Setze werden ins Präteritum.'),text('The past passive uses wurde for a singular subject and wurden for a plural subject.','Im Präteritum steht bei einem Subjekt im Singular wurde und im Plural wurden.'),[
 ['Die Unterlagen ___ gestern geprüft. (werden, Präteritum)','wurden'],['Die Lieferung ___ letzte Woche verschickt. (werden, Präteritum)','wurde']]);
add('Passive: perfect tense','Passiv im Perfekt','passive',text('The passive perfect ends with worden.','Im Perfekt des Vorgangspassivs steht am Ende worden.'),text('The passive perfect uses sein + past participle + worden; geworden belongs to the full verb werden.','Das Passiv im Perfekt wird mit sein, Partizip II und worden gebildet. Geworden gehört zum Vollverb werden.'),[
 ['Der Vertrag ist unterschrieben ___. (Passiv, Perfekt)','worden'],['Die Geräte sind repariert ___. (Passiv, Perfekt)','worden']]);
add('Passive with a modal verb','Passiv mit Modalverb','passive',text('After a modal, use participle plus werden.','Nach einem Modalverb stehen Partizip II und werden.'),text('A modal passive uses the infinitive werden after the participle: muss geprüft werden.','Beim Passiv mit Modalverb folgt werden auf das Partizip: muss geprüft werden.'),[
 ['Der Antrag muss bis Freitag geprüft ___. (Passivinfinitiv)','werden'],['Die Daten können digital übermittelt ___. (Passivinfinitiv)','werden']]);
add('Unreal conditions with hätte','Irreale Bedingungen mit hätte','conditional',text('Use Konjunktiv II of haben.','Verwende den Konjunktiv II von haben.'),text('Hätte expresses an unreal present condition with a singular subject: Wenn ich mehr Zeit hätte …','Hätte drückt eine irreale Bedingung aus: Wenn ich mehr Zeit hätte …'),[
 ['Wenn ich mehr Zeit ___, würde ich den Kurs besuchen. (haben, Konjunktiv II)','hätte'],['Wenn sie einen Führerschein ___, könnte sie zur Arbeit fahren. (haben, Konjunktiv II)','hätte']]);
add('Polite requests with könnte','Höfliche Bitten mit könnte','conditional',text('Use Konjunktiv II of können.','Verwende den Konjunktiv II von können.'),text('Könnten Sie … is a polite request; könntest du … addresses one familiar person.','Könnten Sie … ist eine höfliche Bitte. Könntest du … richtet sich an eine vertraute Person.'),[
 ['___ Sie mir bitte die Unterlagen schicken? (können, Konjunktiv II)','Könnten'],['___ du mir kurz helfen? (können, Konjunktiv II)','Könntest']]);
add('Unreal past: hätte','Irreale Vergangenheit mit hätte','conditional',text('Use hätte with a past participle.','Verwende hätte mit einem Partizip II.'),text('Hätte + participle expresses an unreal past event for verbs that form the perfect with haben.','Hätte und Partizip II beschreiben ein irreales Ereignis in der Vergangenheit bei Verben mit haben.'),[
 ['Wenn ich früher gelernt ___, hätte ich die Prüfung bestanden. (haben, Konjunktiv II)','hätte'],['Wenn er die Nachricht gelesen ___, hätte er geantwortet. (haben, Konjunktiv II)','hätte']]);
add('Unreal past: wäre','Irreale Vergangenheit mit wäre','conditional',text('Use wäre with verbs whose perfect uses sein.','Verwende wäre bei Verben, deren Perfekt mit sein gebildet wird.'),text('Wäre + participle expresses an unreal past event with verbs such as kommen and fahren.','Wäre und Partizip II beschreiben ein irreales vergangenes Ereignis mit Verben wie kommen und fahren.'),[
 ['Wenn der Bus pünktlich gekommen ___, hätten wir den Zug erreicht. (sein, Konjunktiv II)','wäre'],['Wenn ich früher losgefahren ___, hätte ich den Termin geschafft. (sein, Konjunktiv II)','wäre']]);
add('Concession with obwohl','Gegensatz mit obwohl','connectors',text('Obwohl introduces a subordinate clause.','Obwohl leitet einen Nebensatz ein.'),text('After obwohl the conjugated verb goes to the end: obwohl … regnet / … ist.','Nach obwohl steht das konjugierte Verb am Ende: obwohl … regnet / … ist.'),[
 ['Obwohl es stark ___, fahren wir mit dem Rad. (regnen, Präsens)','regnet'],['Obwohl die Aufgabe schwierig ___, geben wir nicht auf. (sein, Präsens)','ist']]);
add('Cause with da','Begründung mit da','connectors',text('Da introduces a reason and places the verb last.','Da leitet eine Begründung ein; das Verb steht am Ende.'),text('In a da clause the conjugated verb stands last.','Im Nebensatz mit da steht das konjugierte Verb am Ende.'),[
 ['Da die Kollegin heute ___, übernimmt Tim ihre Aufgaben. (fehlen, Präsens)','fehlt'],['Da der Drucker nicht ___, schicken wir die Datei per E-Mail. (funktionieren, Präsens)','funktioniert']]);
add('Consequence with sodass','Folge mit sodass','connectors',text('Sodass introduces the consequence in a subordinate clause.','Sodass leitet die Folge in einem Nebensatz ein.'),text('A sodass clause places the conjugated verb at the end.','Im Nebensatz mit sodass steht das konjugierte Verb am Ende.'),[
 ['Der Zug hatte Verspätung, sodass ich zu spät ___. (ankommen, Präteritum)','ankam'],['Die Erklärung war klar, sodass alle den Ablauf ___. (verstehen, Präteritum)','verstanden']]);
add('Purpose: um … zu','Absicht mit um … zu','infinitive',text('Use zu before the infinitive.','Vor dem Infinitiv steht zu.'),text('Um … zu expresses purpose when both clauses have the same subject.','Um … zu beschreibt eine Absicht, wenn beide Satzteile dasselbe Subjekt haben.'),[
 ['Ich besuche einen Kurs, um meine Aussprache ___ verbessern. (Infinitivpartikel)','zu'],['Sie spart Geld, um eine Weiterbildung ___ finanzieren. (Infinitivpartikel)','zu']]);
add('Infinitives of separable verbs','Infinitiv mit zu bei trennbaren Verben','infinitive',text('Put zu between the prefix and the verb stem.','Setze zu zwischen Vorsilbe und Verbstamm.'),text('With separable verbs, zu is inserted: vorbereiten → vorzubereiten; teilnehmen → teilzunehmen.','Bei trennbaren Verben steht zu im Wort: vorbereiten → vorzubereiten; teilnehmen → teilzunehmen.'),[
 ['Ich habe vor, mich auf das Gespräch ___. (vorbereiten, Infinitiv mit zu)','vorzubereiten'],['Sie hat beschlossen, am Seminar ___. (teilnehmen, Infinitiv mit zu)','teilzunehmen']]);
add('Relative pronouns: accusative','Relativpronomen im Akkusativ','relative',text('The relative pronoun is the object of the relative clause.','Das Relativpronomen ist das Objekt im Relativsatz.'),text('For a masculine accusative antecedent use den; for a neuter one use das.','Im Akkusativ steht bei einem maskulinen Bezugswort den, bei einem neutralen das.'),[
 ['Der Vertrag, ___ ich gestern unterschrieben habe, gilt ab Mai. (Relativpronomen)','den'],['Das Angebot, ___ wir erhalten haben, ist günstig. (Relativpronomen)','das']]);
add('Relative pronouns: dative','Relativpronomen im Dativ','relative',text('Helfen and mit require the dative.','Helfen und mit verlangen den Dativ.'),text('The dative relative pronouns are dem for masculine/neuter and der for feminine.','Im Dativ lauten die Relativpronomen dem bei maskulinen und neutralen, der bei femininen Bezugswörtern.'),[
 ['Die Kollegin, ___ ich geholfen habe, bedankt sich. (Relativpronomen)','der'],['Der Kunde, mit ___ ich gesprochen habe, kommt morgen. (Relativpronomen)','dem']]);
add('Relative pronouns: genitive','Relativpronomen im Genitiv','relative',text('Dessen and deren express possession.','Dessen und deren drücken Zugehörigkeit aus.'),text('Dessen refers to a masculine or neuter antecedent, deren to a feminine or plural antecedent.','Dessen bezieht sich auf ein maskulines oder neutrales Bezugswort, deren auf ein feminines Bezugswort oder den Plural.'),[
 ['Der Mitarbeiter, ___ Vorschlag wir besprochen haben, ist heute da. (Relativpronomen im Genitiv)','dessen'],['Die Firma, ___ Produkte wir verkaufen, hat ihren Sitz in Köln. (Relativpronomen im Genitiv)','deren']]);
add('Genitive after trotz','Genitiv nach trotz','cases',text('Use the standard written genitive form.','Verwende den Genitiv der Standardschriftsprache.'),text('In standard written German trotz commonly takes the genitive: trotz des Regens / der Verspätung.','In der Standardschriftsprache steht trotz meist mit Genitiv: trotz des Regens / der Verspätung.'),[
 ['Trotz ___ starken Regens fand die Veranstaltung statt. (der, Genitiv)','des'],['Trotz ___ Verspätung erreichten wir den Anschluss. (die, Genitiv)','der']]);
add('Genitive after während','Genitiv nach während','cases',text('Here während is a preposition, not a conjunction.','Hier ist während eine Präposition und keine Konjunktion.'),text('As a preposition in standard written German, während takes the genitive.','Als Präposition steht während in der Standardschriftsprache mit dem Genitiv.'),[
 ['Während ___ Gesprächs klingelte das Telefon. (das, Genitiv)','des'],['Während ___ Besprechung machen wir Notizen. (die, Genitiv)','der']]);
add('Adjectives in the genitive','Adjektive im Genitiv','adjective',text('After the definite article, the adjective ends in -en here.','Nach dem bestimmten Artikel endet das Adjektiv hier auf -en.'),text('After des in these genitive phrases the adjective has the weak ending -en.','Nach des erhält das Adjektiv in diesen Genitivgruppen die schwache Endung -en.'),[
 ['Wegen des ___ Wetters wurde das Fest abgesagt. (schlecht)','schlechten'],['Die Folgen des ___ Fehlers waren teuer. (technisch)','technischen']]);
add('Adjectives without an article','Adjektive ohne Artikel','adjective',text('Use strong adjective endings with no article.','Ohne Artikel werden Adjektive stark dekliniert.'),text('Without an article, a masculine dative adjective ends in -em; a plural dative adjective ends in -en.','Ohne Artikel endet das Adjektiv im Dativ Maskulinum auf -em, im Dativ Plural auf -en.'),[
 ['Mit ___ Interesse habe ich Ihre Anzeige gelesen. (groß)','großem'],['Mit ___ Kollegen arbeiten wir gern zusammen. (zuverlässig)','zuverlässigen']]);
add('Depend on: abhängen von','Abhängen von','verb_preposition',text('Learn the fixed preposition with abhängen.','Lerne die feste Präposition zu abhängen.'),text('Abhängen is used with von + dative: von der Erfahrung / vom Wetter.','Abhängen steht mit von und Dativ: von der Erfahrung / vom Wetter.'),[
 ['Der Erfolg hängt ___ der Erfahrung des Teams ab. (Präposition zu abhängen)','von'],['Unsere Planung hängt ___ dem Wetter ab. (Präposition zu abhängen)','von']]);
add('Participate: teilnehmen an','Teilnehmen an','verb_preposition',text('Learn the fixed preposition with teilnehmen.','Lerne die feste Präposition zu teilnehmen.'),text('Teilnehmen is used with an + dative.','Teilnehmen steht mit an und Dativ.'),[
 ['Sie nimmt ___ einer Fortbildung teil. (Präposition zu teilnehmen)','an'],['Wir nehmen ___ dem Projekt teil. (Präposition zu teilnehmen)','an']]);
add('Convince: überzeugen von','Überzeugen von','verb_preposition',text('Learn jemanden von etwas überzeugen.','Lerne jemanden von etwas überzeugen.'),text('Überzeugen takes a person as accusative object and von + dative for the idea.','Überzeugen hat ein Akkusativobjekt für die Person; die Sache folgt mit von und Dativ.'),[
 ['Die Daten überzeugen mich ___ der Qualität. (Präposition zu überzeugen)','von'],['Sie überzeugt das Team ___ ihrem Vorschlag. (Präposition zu überzeugen)','von']]);
add('Deal with: sich befassen mit','Sich befassen mit','verb_preposition',text('Learn the fixed preposition with sich befassen.','Lerne die feste Präposition zu sich befassen.'),text('Sich befassen takes mit + dative.','Sich befassen steht mit mit und Dativ.'),[
 ['Wir befassen uns ___ den neuen Regeln. (Präposition zu sich befassen)','mit'],['Er befasst sich ___ der Auswertung. (Präposition zu sich befassen)','mit']]);
add('Result from: sich ergeben aus','Sich ergeben aus','verb_preposition',text('Here ergeben means result from, not surrender.','Ergeben bedeutet hier resultieren, nicht kapitulieren.'),text('Sich aus etwas ergeben means to result from it: Möglichkeiten ergeben sich aus dem Gespräch.','Sich aus etwas ergeben bedeutet daraus resultieren: Möglichkeiten ergeben sich aus dem Gespräch.'),[
 ['Neue Möglichkeiten ergeben sich ___ dem Gespräch. (Präposition zu sich ergeben)','aus'],['Die nächsten Schritte ergeben sich ___ der Analyse. (Präposition zu sich ergeben)','aus']]);
add('Submit an application','Einen Antrag stellen','work_vocabulary',text('Use the specified verb in the present tense.','Setze das angegebene Verb ins Präsens.'),text('Einen Antrag stellen is the conventional expression for applying formally.','Einen Antrag stellen ist eine übliche Verbindung für eine formelle Beantragung.'),[
 ['Ich ___ einen Antrag auf Förderung. (stellen, Präsens)','stelle'],['Sie ___ einen Antrag auf Weiterbildung. (stellen, Präsens, 3. Person Singular)','stellt']]);
add('Make a decision','Eine Entscheidung treffen','work_vocabulary',text('Treffen changes its stem vowel in the singular.','Treffen verändert im Singular seinen Stammvokal.'),text('Eine Entscheidung treffen is a fixed collocation. The singular forms are trifft and triffst.','Eine Entscheidung treffen ist eine feste Verbindung. Die Singularformen lauten trifft und triffst.'),[
 ['Der Vorstand ___ morgen eine Entscheidung. (treffen, Präsens)','trifft'],['Du ___ die Entscheidung selbst. (treffen, Präsens)','triffst']]);
add('Take responsibility','Verantwortung übernehmen','work_vocabulary',text('Übernehmen changes its stem vowel in the singular.','Übernehmen verändert im Singular seinen Stammvokal.'),text('Verantwortung übernehmen means to take responsibility; use übernimmt / übernimmst.','Verantwortung übernehmen bedeutet für etwas verantwortlich werden; die Formen lauten übernimmt / übernimmst.'),[
 ['Die Leiterin ___ die Verantwortung für das Projekt. (übernehmen, Präsens)','übernimmt'],['Du ___ die Verantwortung für die Abrechnung. (übernehmen, Präsens)','übernimmst']]);
add('Meet a deadline','Eine Frist einhalten','work_vocabulary',text('Einhalten is separable and changes its stem vowel.','Einhalten ist trennbar und verändert seinen Stammvokal.'),text('Eine Frist einhalten means to meet a deadline. The singular stem is hält / hältst.','Eine Frist einhalten bedeutet rechtzeitig fertig werden. Im Singular stehen hält / hältst.'),[
 ['Das Team ___ die Frist ein. (einhalten, Präsens; nur der konjugierte Teil)','hält'],['Du ___ die vereinbarte Frist ein. (einhalten, Präsens; nur der konjugierte Teil)','hältst']]);
add('Fulfil requirements','Voraussetzungen erfüllen','work_vocabulary',text('Use the specified verb in the present tense.','Setze das angegebene Verb ins Präsens.'),text('Voraussetzungen erfüllen means to meet the prerequisites for something.','Voraussetzungen erfüllen bedeutet den Anforderungen für etwas entsprechen.'),[
 ['Ich ___ alle Voraussetzungen für die Stelle. (erfüllen, Präsens)','erfülle'],['Die Bewerberin ___ die fachlichen Voraussetzungen. (erfüllen, Präsens)','erfüllt']]);
writeFileSync(destination, JSON.stringify({schemaVersion:1,status:'agent-authored-draft',publicationApproved:false,targets},null,2)+'\n');
console.log(`Prepared ${targets.length} B2 targets / ${targets.length*2} variants; pending independent review.`);
