// Generated by contracts/scripts/generate.mjs v1. Do not edit.
package com.germanverbmaster.android.foundation.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.*

@Serializable
data class Option(
    val id: String,
    val text: String
) {
    init {
        require(id.length >= 1) { "Invalid Option.id" }
        require(text.length >= 1) { "Invalid Option.text" }
    }
}

@Serializable
data class Slot(
    val id: String,
    val label: String
) {
    init {
        require(id.length >= 1) { "Invalid Slot.id" }
        require(label.length >= 1) { "Invalid Slot.label" }
    }
}

@Serializable
data class SlotValue(
    val slotId: String,
    val text: String
) {
    init {
        require(slotId.length >= 1) { "Invalid SlotValue.slotId" }
    }
}

@Serializable
data class LocalizedText(
    val en: String,
    val de: String
) {
    init {
        require(en.length >= 1) { "Invalid LocalizedText.en" }
        require(de.length >= 1) { "Invalid LocalizedText.de" }
    }
}

@Serializable
@SerialName("short_answer")
data class ExerciseShortAnswer(
    override val schemaVersion: Int,
    override val id: String,
    override val revision: Int,
    override val targetId: String,
    override val prompt: String,
    override val instruction: LocalizedText,
    override val hint: LocalizedText
) : Exercise() {
    init {
        require(schemaVersion == 1) { "Invalid ExerciseShortAnswer.schemaVersion" }
        require(schemaVersion <= 2147483647) { "Invalid ExerciseShortAnswer.schemaVersion" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(id)) { "Invalid ExerciseShortAnswer.id" }
        require(revision >= 1) { "Invalid ExerciseShortAnswer.revision" }
        require(revision <= 2147483647) { "Invalid ExerciseShortAnswer.revision" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(targetId)) { "Invalid ExerciseShortAnswer.targetId" }
        require(prompt.length >= 1) { "Invalid ExerciseShortAnswer.prompt" }
    }
}

@Serializable
@SerialName("choice")
data class ExerciseChoice(
    override val schemaVersion: Int,
    override val id: String,
    override val revision: Int,
    override val targetId: String,
    override val prompt: String,
    override val instruction: LocalizedText,
    override val hint: LocalizedText,
    val options: List<Option>
) : Exercise() {
    init {
        require(schemaVersion == 1) { "Invalid ExerciseChoice.schemaVersion" }
        require(schemaVersion <= 2147483647) { "Invalid ExerciseChoice.schemaVersion" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(id)) { "Invalid ExerciseChoice.id" }
        require(revision >= 1) { "Invalid ExerciseChoice.revision" }
        require(revision <= 2147483647) { "Invalid ExerciseChoice.revision" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(targetId)) { "Invalid ExerciseChoice.targetId" }
        require(prompt.length >= 1) { "Invalid ExerciseChoice.prompt" }
        require(options.size >= 2) { "Invalid ExerciseChoice.options" }
    }
}

@Serializable
@SerialName("cloze")
data class ExerciseCloze(
    override val schemaVersion: Int,
    override val id: String,
    override val revision: Int,
    override val targetId: String,
    override val prompt: String,
    override val instruction: LocalizedText,
    override val hint: LocalizedText,
    val slots: List<Slot>
) : Exercise() {
    init {
        require(schemaVersion == 1) { "Invalid ExerciseCloze.schemaVersion" }
        require(schemaVersion <= 2147483647) { "Invalid ExerciseCloze.schemaVersion" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(id)) { "Invalid ExerciseCloze.id" }
        require(revision >= 1) { "Invalid ExerciseCloze.revision" }
        require(revision <= 2147483647) { "Invalid ExerciseCloze.revision" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(targetId)) { "Invalid ExerciseCloze.targetId" }
        require(prompt.length >= 1) { "Invalid ExerciseCloze.prompt" }
        require(slots.size >= 1) { "Invalid ExerciseCloze.slots" }
    }
}

@Serializable
@SerialName("word_order")
data class ExerciseWordOrder(
    override val schemaVersion: Int,
    override val id: String,
    override val revision: Int,
    override val targetId: String,
    override val prompt: String,
    override val instruction: LocalizedText,
    override val hint: LocalizedText,
    val tokens: List<Option>
) : Exercise() {
    init {
        require(schemaVersion == 1) { "Invalid ExerciseWordOrder.schemaVersion" }
        require(schemaVersion <= 2147483647) { "Invalid ExerciseWordOrder.schemaVersion" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(id)) { "Invalid ExerciseWordOrder.id" }
        require(revision >= 1) { "Invalid ExerciseWordOrder.revision" }
        require(revision <= 2147483647) { "Invalid ExerciseWordOrder.revision" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(targetId)) { "Invalid ExerciseWordOrder.targetId" }
        require(prompt.length >= 1) { "Invalid ExerciseWordOrder.prompt" }
        require(tokens.size >= 2) { "Invalid ExerciseWordOrder.tokens" }
    }
}

@Serializable
@SerialName("multi_slot")
data class ExerciseMultiSlot(
    override val schemaVersion: Int,
    override val id: String,
    override val revision: Int,
    override val targetId: String,
    override val prompt: String,
    override val instruction: LocalizedText,
    override val hint: LocalizedText,
    val slots: List<Slot>
) : Exercise() {
    init {
        require(schemaVersion == 1) { "Invalid ExerciseMultiSlot.schemaVersion" }
        require(schemaVersion <= 2147483647) { "Invalid ExerciseMultiSlot.schemaVersion" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(id)) { "Invalid ExerciseMultiSlot.id" }
        require(revision >= 1) { "Invalid ExerciseMultiSlot.revision" }
        require(revision <= 2147483647) { "Invalid ExerciseMultiSlot.revision" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(targetId)) { "Invalid ExerciseMultiSlot.targetId" }
        require(prompt.length >= 1) { "Invalid ExerciseMultiSlot.prompt" }
        require(slots.size >= 2) { "Invalid ExerciseMultiSlot.slots" }
    }
}

@Serializable
@SerialName("short_answer")
data class AnswerShortAnswer(
    val text: String
) : Answer() {
    init {

    }
}

@Serializable
@SerialName("choice")
data class AnswerChoice(
    val optionId: String
) : Answer() {
    init {
        require(optionId.length >= 1) { "Invalid AnswerChoice.optionId" }
    }
}

@Serializable
@SerialName("cloze")
data class AnswerCloze(
    val values: List<SlotValue>
) : Answer() {
    init {
        require(values.size >= 1) { "Invalid AnswerCloze.values" }
    }
}

@Serializable
@SerialName("word_order")
data class AnswerWordOrder(
    val tokenIds: List<String>
) : Answer() {
    init {
        require(tokenIds.size >= 2) { "Invalid AnswerWordOrder.tokenIds" }
        require(tokenIds.distinct().size == tokenIds.size) { "Invalid AnswerWordOrder.tokenIds" }
        require(tokenIds.all { it.length >= 1 }) { "Invalid AnswerWordOrder.tokenIds" }
    }
}

@Serializable
@SerialName("multi_slot")
data class AnswerMultiSlot(
    val values: List<SlotValue>
) : Answer() {
    init {
        require(values.size >= 2) { "Invalid AnswerMultiSlot.values" }
    }
}

@Serializable
@OptIn(kotlinx.serialization.ExperimentalSerializationApi::class)
@JsonClassDiscriminator("type")
sealed class Exercise {
    abstract val schemaVersion: Int
    abstract val id: String
    abstract val revision: Int
    abstract val targetId: String
    abstract val prompt: String
    abstract val instruction: LocalizedText
    abstract val hint: LocalizedText
}

@Serializable
@OptIn(kotlinx.serialization.ExperimentalSerializationApi::class)
@JsonClassDiscriminator("type")
sealed class Answer {

}

@Serializable
data class Question(
    val id: String,
    val exercise: Exercise
) {
    init {
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(id)) { "Invalid Question.id" }
    }
}

@Serializable
data class Session(
    val apiVersion: String,
    val id: String,
    val contentReleaseId: String,
    val questions: List<Question>
) {
    init {
        require(apiVersion == "v2") { "Invalid Session.apiVersion" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(id)) { "Invalid Session.id" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(contentReleaseId)) { "Invalid Session.contentReleaseId" }
        require(questions.size >= 1) { "Invalid Session.questions" }
        require(questions.size <= 50) { "Invalid Session.questions" }
    }
}

@Serializable
data class Attempt(
    val attemptId: String,
    val sessionQuestionId: String,
    val exerciseRevision: Int,
    val deviceId: String,
    val answer: Answer,
    val assistance: List<String>,
    val answeredAt: String,
    val clientSequence: Int
) {
    init {
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(attemptId)) { "Invalid Attempt.attemptId" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(sessionQuestionId)) { "Invalid Attempt.sessionQuestionId" }
        require(exerciseRevision >= 1) { "Invalid Attempt.exerciseRevision" }
        require(exerciseRevision <= 2147483647) { "Invalid Attempt.exerciseRevision" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(deviceId)) { "Invalid Attempt.deviceId" }
        require(assistance.all { it in setOf("hint", "reveal") }) { "Invalid Attempt.assistance" }
        require(Regex("^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{3})?Z$").matches(answeredAt)) { "Invalid Attempt.answeredAt" }
        require(runCatching { java.time.Instant.parse(answeredAt).toString() == answeredAt.replace(".000Z", "Z") }.getOrDefault(false)) { "Invalid Attempt.answeredAt" }
        require(clientSequence >= 0) { "Invalid Attempt.clientSequence" }
        require(clientSequence <= 2147483647) { "Invalid Attempt.clientSequence" }
    }
}

@Serializable
data class AttemptBatch(
    val apiVersion: String,
    val attempts: List<Attempt>
) {
    init {
        require(apiVersion == "v2") { "Invalid AttemptBatch.apiVersion" }
        require(attempts.size >= 1) { "Invalid AttemptBatch.attempts" }
        require(attempts.size <= 50) { "Invalid AttemptBatch.attempts" }
    }
}

@Serializable
data class ApiError(
    val code: String,
    val message: String,
    val requestId: String,
    val retryable: Boolean
) {
    init {
        require(code.length >= 1) { "Invalid ApiError.code" }
        require(message.length >= 1) { "Invalid ApiError.message" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(requestId)) { "Invalid ApiError.requestId" }
    }
}

@Serializable
data class SessionRequest(
    val apiVersion: String,
    val requestId: String,
    val questionCount: Int,
    val capabilities: List<String>
) {
    init {
        require(apiVersion == "v2") { "Invalid SessionRequest.apiVersion" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(requestId)) { "Invalid SessionRequest.requestId" }
        require(questionCount >= 1) { "Invalid SessionRequest.questionCount" }
        require(questionCount <= 50) { "Invalid SessionRequest.questionCount" }
        require(capabilities.size >= 1) { "Invalid SessionRequest.capabilities" }
        require(capabilities.distinct().size == capabilities.size) { "Invalid SessionRequest.capabilities" }
        require(capabilities.all { it in setOf("short_answer@1", "choice@1", "cloze@1", "word_order@1", "multi_slot@1") }) { "Invalid SessionRequest.capabilities" }
    }
}

@Serializable
data class Evaluation(
    val outcome: String,
    val policyVersion: String,
    val explanation: LocalizedText,
    val acceptedAnswer: Answer,
    val assisted: Boolean
) {
    init {
        require(outcome in setOf("correct", "incorrect", "skipped")) { "Invalid Evaluation.outcome" }
        require(policyVersion.length >= 1) { "Invalid Evaluation.policyVersion" }
    }
}

@Serializable
@SerialName("accepted")
data class AttemptAcknowledgment(
    override val attemptId: String,
    val evaluation: Evaluation,
    val serverSequence: Int
) : Acknowledgment() {
    init {
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(attemptId)) { "Invalid AttemptAcknowledgment.attemptId" }
        require(serverSequence >= 0) { "Invalid AttemptAcknowledgment.serverSequence" }
        require(serverSequence <= 2147483647) { "Invalid AttemptAcknowledgment.serverSequence" }
    }
}

@Serializable
@SerialName("rejected")
data class AttemptRejection(
    override val attemptId: String,
    val error: ApiError
) : Acknowledgment() {
    init {
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(attemptId)) { "Invalid AttemptRejection.attemptId" }
    }
}

@Serializable
@SerialName("duplicate")
data class AttemptDuplicate(
    override val attemptId: String,
    val evaluation: Evaluation,
    val serverSequence: Int
) : Acknowledgment() {
    init {
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(attemptId)) { "Invalid AttemptDuplicate.attemptId" }
        require(serverSequence >= 0) { "Invalid AttemptDuplicate.serverSequence" }
        require(serverSequence <= 2147483647) { "Invalid AttemptDuplicate.serverSequence" }
    }
}

@Serializable
@OptIn(kotlinx.serialization.ExperimentalSerializationApi::class)
@JsonClassDiscriminator("status")
sealed class Acknowledgment {
    abstract val attemptId: String
}

@Serializable
data class AttemptBatchResponse(
    val apiVersion: String,
    val acknowledgments: List<Acknowledgment>
) {
    init {
        require(apiVersion == "v2") { "Invalid AttemptBatchResponse.apiVersion" }
        require(acknowledgments.size >= 1) { "Invalid AttemptBatchResponse.acknowledgments" }
        require(acknowledgments.size <= 50) { "Invalid AttemptBatchResponse.acknowledgments" }
    }
}

@Serializable
data class ExposureEvent(
    val eventId: String,
    val sessionQuestionId: String,
    val exerciseRevision: Int,
    val deviceId: String,
    val disposition: String,
    val occurredAt: String
) {
    init {
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(eventId)) { "Invalid ExposureEvent.eventId" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(sessionQuestionId)) { "Invalid ExposureEvent.sessionQuestionId" }
        require(exerciseRevision >= 1) { "Invalid ExposureEvent.exerciseRevision" }
        require(exerciseRevision <= 2147483647) { "Invalid ExposureEvent.exerciseRevision" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(deviceId)) { "Invalid ExposureEvent.deviceId" }
        require(disposition in setOf("skip", "exposure")) { "Invalid ExposureEvent.disposition" }
        require(Regex("^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{3})?Z$").matches(occurredAt)) { "Invalid ExposureEvent.occurredAt" }
        require(runCatching { java.time.Instant.parse(occurredAt).toString() == occurredAt.replace(".000Z", "Z") }.getOrDefault(false)) { "Invalid ExposureEvent.occurredAt" }
    }
}

@Serializable
data class ExposureBatch(
    val apiVersion: String,
    val events: List<ExposureEvent>
) {
    init {
        require(apiVersion == "v2") { "Invalid ExposureBatch.apiVersion" }
        require(events.size >= 1) { "Invalid ExposureBatch.events" }
        require(events.size <= 50) { "Invalid ExposureBatch.events" }
    }
}

@Serializable
@SerialName("accepted")
data class ExposureAccepted(
    override val eventId: String,
    val serverSequence: Int
) : ExposureAcknowledgment() {
    init {
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(eventId)) { "Invalid ExposureAccepted.eventId" }
        require(serverSequence >= 1) { "Invalid ExposureAccepted.serverSequence" }
        require(serverSequence <= 2147483647) { "Invalid ExposureAccepted.serverSequence" }
    }
}

@Serializable
@SerialName("duplicate")
data class ExposureDuplicate(
    override val eventId: String,
    val serverSequence: Int
) : ExposureAcknowledgment() {
    init {
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(eventId)) { "Invalid ExposureDuplicate.eventId" }
        require(serverSequence >= 1) { "Invalid ExposureDuplicate.serverSequence" }
        require(serverSequence <= 2147483647) { "Invalid ExposureDuplicate.serverSequence" }
    }
}

@Serializable
@SerialName("rejected")
data class ExposureRejected(
    override val eventId: String,
    val error: ApiError
) : ExposureAcknowledgment() {
    init {
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(eventId)) { "Invalid ExposureRejected.eventId" }
    }
}

@Serializable
@OptIn(kotlinx.serialization.ExperimentalSerializationApi::class)
@JsonClassDiscriminator("status")
sealed class ExposureAcknowledgment {
    abstract val eventId: String
}

@Serializable
data class ExposureBatchResponse(
    val apiVersion: String,
    val acknowledgments: List<ExposureAcknowledgment>
) {
    init {
        require(apiVersion == "v2") { "Invalid ExposureBatchResponse.apiVersion" }
        require(acknowledgments.size >= 1) { "Invalid ExposureBatchResponse.acknowledgments" }
        require(acknowledgments.size <= 50) { "Invalid ExposureBatchResponse.acknowledgments" }
    }
}

@Serializable
data class TargetSchedule(
    val dueAt: String,
    val intervalStep: Int,
    val intervalDays: Int
) {
    init {
        require(dueAt.length >= 1) { "Invalid TargetSchedule.dueAt" }
        require(Regex("^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{3})?Z$").matches(dueAt)) { "Invalid TargetSchedule.dueAt" }
        require(runCatching { java.time.Instant.parse(dueAt).toString() == dueAt.replace(".000Z", "Z") }.getOrDefault(false)) { "Invalid TargetSchedule.dueAt" }
        require(intervalStep >= 0) { "Invalid TargetSchedule.intervalStep" }
        require(intervalStep <= 2147483647) { "Invalid TargetSchedule.intervalStep" }
        require(intervalDays >= 0) { "Invalid TargetSchedule.intervalDays" }
        require(intervalDays <= 2147483647) { "Invalid TargetSchedule.intervalDays" }
    }
}

@Serializable
data class ConfirmedTarget(
    val targetId: String,
    val policyVersion: String,
    val state: String,
    val exposureCount: Int,
    val qualifyingCheckCount: Int,
    val everMastered: Boolean,
    val lapseCount: Int,
    val lastSequence: Int,
    val schedule: List<TargetSchedule>,
    val isDue: Boolean
) {
    init {
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(targetId)) { "Invalid ConfirmedTarget.targetId" }
        require(policyVersion == "retained-evidence-v1") { "Invalid ConfirmedTarget.policyVersion" }
        require(state in setOf("new", "learning", "needs_practice", "improving", "mastered")) { "Invalid ConfirmedTarget.state" }
        require(exposureCount >= 0) { "Invalid ConfirmedTarget.exposureCount" }
        require(exposureCount <= 2147483647) { "Invalid ConfirmedTarget.exposureCount" }
        require(qualifyingCheckCount >= 0) { "Invalid ConfirmedTarget.qualifyingCheckCount" }
        require(qualifyingCheckCount <= 2147483647) { "Invalid ConfirmedTarget.qualifyingCheckCount" }
        require(lapseCount >= 0) { "Invalid ConfirmedTarget.lapseCount" }
        require(lapseCount <= 2147483647) { "Invalid ConfirmedTarget.lapseCount" }
        require(lastSequence >= 0) { "Invalid ConfirmedTarget.lastSequence" }
        require(lastSequence <= 2147483647) { "Invalid ConfirmedTarget.lastSequence" }
        require(schedule.size <= 1) { "Invalid ConfirmedTarget.schedule" }
    }
}

@Serializable
data class TargetPage(
    val apiVersion: String,
    val generatedAt: String,
    val targets: List<ConfirmedTarget>,
    val nextPageCursor: String,
    val syncCursor: String
) {
    init {
        require(apiVersion == "v2") { "Invalid TargetPage.apiVersion" }
        require(generatedAt.length >= 1) { "Invalid TargetPage.generatedAt" }
        require(Regex("^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(?:\\.\\d{3})?Z$").matches(generatedAt)) { "Invalid TargetPage.generatedAt" }
        require(runCatching { java.time.Instant.parse(generatedAt).toString() == generatedAt.replace(".000Z", "Z") }.getOrDefault(false)) { "Invalid TargetPage.generatedAt" }
        require(targets.size <= 100) { "Invalid TargetPage.targets" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(syncCursor)) { "Invalid TargetPage.syncCursor" }
    }
}

@Serializable
data class TargetChange(
    val sequence: Int,
    val operation: String,
    val target: ConfirmedTarget
) {
    init {
        require(sequence >= 0) { "Invalid TargetChange.sequence" }
        require(sequence <= 2147483647) { "Invalid TargetChange.sequence" }
        require(operation == "upsert") { "Invalid TargetChange.operation" }
    }
}

@Serializable
data class SyncPage(
    val apiVersion: String,
    val changes: List<TargetChange>,
    val nextCursor: String,
    val hasMore: Boolean
) {
    init {
        require(apiVersion == "v2") { "Invalid SyncPage.apiVersion" }
        require(changes.size <= 100) { "Invalid SyncPage.changes" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(nextCursor)) { "Invalid SyncPage.nextCursor" }
    }
}

object ContractShape {
    fun checkOption(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("id", "text")); run { val p = o.getValue("id") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("text") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) } } }
    fun checkSlot(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("id", "label")); run { val p = o.getValue("id") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("label") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) } } }
    fun checkSlotValue(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("slotId", "text")); run { val p = o.getValue("slotId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("text") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) } } }
    fun checkLocalizedText(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("en", "de")); run { val p = o.getValue("en") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("de") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) } } }
    fun checkExerciseShortAnswer(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("type", "schemaVersion", "id", "revision", "targetId", "prompt", "instruction", "hint")); run { val p = o.getValue("type") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("schemaVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("id") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("revision") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("targetId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("prompt") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkLocalizedText(o.getValue("instruction")); checkLocalizedText(o.getValue("hint")) } }
    fun checkExerciseChoice(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("type", "schemaVersion", "id", "revision", "targetId", "prompt", "instruction", "hint", "options")); run { val p = o.getValue("type") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("schemaVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("id") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("revision") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("targetId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("prompt") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkLocalizedText(o.getValue("instruction")); checkLocalizedText(o.getValue("hint")); run { val a = o.getValue("options") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkOption(item) } } } }
    fun checkExerciseCloze(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("type", "schemaVersion", "id", "revision", "targetId", "prompt", "instruction", "hint", "slots")); run { val p = o.getValue("type") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("schemaVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("id") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("revision") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("targetId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("prompt") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkLocalizedText(o.getValue("instruction")); checkLocalizedText(o.getValue("hint")); run { val a = o.getValue("slots") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkSlot(item) } } } }
    fun checkExerciseWordOrder(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("type", "schemaVersion", "id", "revision", "targetId", "prompt", "instruction", "hint", "tokens")); run { val p = o.getValue("type") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("schemaVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("id") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("revision") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("targetId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("prompt") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkLocalizedText(o.getValue("instruction")); checkLocalizedText(o.getValue("hint")); run { val a = o.getValue("tokens") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkOption(item) } } } }
    fun checkExerciseMultiSlot(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("type", "schemaVersion", "id", "revision", "targetId", "prompt", "instruction", "hint", "slots")); run { val p = o.getValue("type") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("schemaVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("id") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("revision") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("targetId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("prompt") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkLocalizedText(o.getValue("instruction")); checkLocalizedText(o.getValue("hint")); run { val a = o.getValue("slots") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkSlot(item) } } } }
    fun checkAnswerShortAnswer(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("type", "text")); run { val p = o.getValue("type") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("text") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) } } }
    fun checkAnswerChoice(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("type", "optionId")); run { val p = o.getValue("type") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("optionId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) } } }
    fun checkAnswerCloze(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("type", "values")); run { val p = o.getValue("type") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val a = o.getValue("values") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkSlotValue(item) } } } }
    fun checkAnswerWordOrder(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("type", "tokenIds")); run { val p = o.getValue("type") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val a = o.getValue("tokenIds") as? JsonArray ?: error("Expected array"); a.forEach { item -> run { val p = item as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) } } } } }
    fun checkAnswerMultiSlot(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("type", "values")); run { val p = o.getValue("type") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val a = o.getValue("values") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkSlotValue(item) } } } }
    fun checkExercise(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); val tag=o["type"] as? JsonPrimitive ?: error("Missing discriminator"); require(tag.isString); when(tag.content) { "short_answer" -> checkExerciseShortAnswer(element); "choice" -> checkExerciseChoice(element); "cloze" -> checkExerciseCloze(element); "word_order" -> checkExerciseWordOrder(element); "multi_slot" -> checkExerciseMultiSlot(element); else -> error("Unsupported discriminator") } } }
    fun checkAnswer(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); val tag=o["type"] as? JsonPrimitive ?: error("Missing discriminator"); require(tag.isString); when(tag.content) { "short_answer" -> checkAnswerShortAnswer(element); "choice" -> checkAnswerChoice(element); "cloze" -> checkAnswerCloze(element); "word_order" -> checkAnswerWordOrder(element); "multi_slot" -> checkAnswerMultiSlot(element); else -> error("Unsupported discriminator") } } }
    fun checkQuestion(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("id", "exercise")); run { val p = o.getValue("id") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkExercise(o.getValue("exercise")) } }
    fun checkSession(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("apiVersion", "id", "contentReleaseId", "questions")); run { val p = o.getValue("apiVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("id") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("contentReleaseId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val a = o.getValue("questions") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkQuestion(item) } } } }
    fun checkAttempt(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("attemptId", "sessionQuestionId", "exerciseRevision", "deviceId", "answer", "assistance", "answeredAt", "clientSequence")); run { val p = o.getValue("attemptId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("sessionQuestionId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("exerciseRevision") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("deviceId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkAnswer(o.getValue("answer")); run { val a = o.getValue("assistance") as? JsonArray ?: error("Expected array"); a.forEach { item -> run { val p = item as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) } } }; run { val p = o.getValue("answeredAt") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("clientSequence") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) } } }
    fun checkAttemptBatch(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("apiVersion", "attempts")); run { val p = o.getValue("apiVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val a = o.getValue("attempts") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkAttempt(item) } } } }
    fun checkApiError(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("code", "message", "requestId", "retryable")); run { val p = o.getValue("code") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("message") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("requestId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("retryable") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.booleanOrNull != null) } } }
    fun checkSessionRequest(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("apiVersion", "requestId", "questionCount", "capabilities")); run { val p = o.getValue("apiVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("requestId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("questionCount") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val a = o.getValue("capabilities") as? JsonArray ?: error("Expected array"); a.forEach { item -> run { val p = item as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) } } } } }
    fun checkEvaluation(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("outcome", "policyVersion", "explanation", "acceptedAnswer", "assisted")); run { val p = o.getValue("outcome") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("policyVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkLocalizedText(o.getValue("explanation")); checkAnswer(o.getValue("acceptedAnswer")); run { val p = o.getValue("assisted") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.booleanOrNull != null) } } }
    fun checkAttemptAcknowledgment(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("attemptId", "status", "evaluation", "serverSequence")); run { val p = o.getValue("attemptId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("status") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkEvaluation(o.getValue("evaluation")); run { val p = o.getValue("serverSequence") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) } } }
    fun checkAttemptRejection(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("attemptId", "status", "error")); run { val p = o.getValue("attemptId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("status") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkApiError(o.getValue("error")) } }
    fun checkAttemptDuplicate(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("attemptId", "status", "evaluation", "serverSequence")); run { val p = o.getValue("attemptId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("status") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkEvaluation(o.getValue("evaluation")); run { val p = o.getValue("serverSequence") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) } } }
    fun checkAcknowledgment(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); val tag=o["status"] as? JsonPrimitive ?: error("Missing discriminator"); require(tag.isString); when(tag.content) { "accepted" -> checkAttemptAcknowledgment(element); "duplicate" -> checkAttemptDuplicate(element); "rejected" -> checkAttemptRejection(element); else -> error("Unsupported discriminator") } } }
    fun checkAttemptBatchResponse(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("apiVersion", "acknowledgments")); run { val p = o.getValue("apiVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val a = o.getValue("acknowledgments") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkAcknowledgment(item) } } } }
    fun checkExposureEvent(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("eventId", "sessionQuestionId", "exerciseRevision", "deviceId", "disposition", "occurredAt")); run { val p = o.getValue("eventId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("sessionQuestionId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("exerciseRevision") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("deviceId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("disposition") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("occurredAt") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) } } }
    fun checkExposureBatch(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("apiVersion", "events")); run { val p = o.getValue("apiVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val a = o.getValue("events") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkExposureEvent(item) } } } }
    fun checkExposureAccepted(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("eventId", "status", "serverSequence")); run { val p = o.getValue("eventId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("status") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("serverSequence") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) } } }
    fun checkExposureDuplicate(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("eventId", "status", "serverSequence")); run { val p = o.getValue("eventId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("status") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("serverSequence") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) } } }
    fun checkExposureRejected(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("eventId", "status", "error")); run { val p = o.getValue("eventId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("status") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkApiError(o.getValue("error")) } }
    fun checkExposureAcknowledgment(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); val tag=o["status"] as? JsonPrimitive ?: error("Missing discriminator"); require(tag.isString); when(tag.content) { "accepted" -> checkExposureAccepted(element); "duplicate" -> checkExposureDuplicate(element); "rejected" -> checkExposureRejected(element); else -> error("Unsupported discriminator") } } }
    fun checkExposureBatchResponse(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("apiVersion", "acknowledgments")); run { val p = o.getValue("apiVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val a = o.getValue("acknowledgments") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkExposureAcknowledgment(item) } } } }
    fun checkTargetSchedule(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("dueAt", "intervalStep", "intervalDays")); run { val p = o.getValue("dueAt") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("intervalStep") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("intervalDays") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) } } }
    fun checkConfirmedTarget(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("targetId", "policyVersion", "state", "exposureCount", "qualifyingCheckCount", "everMastered", "lapseCount", "lastSequence", "schedule", "isDue")); run { val p = o.getValue("targetId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("policyVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("state") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("exposureCount") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("qualifyingCheckCount") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("everMastered") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.booleanOrNull != null) }; run { val p = o.getValue("lapseCount") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("lastSequence") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val a = o.getValue("schedule") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkTargetSchedule(item) } }; run { val p = o.getValue("isDue") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.booleanOrNull != null) } } }
    fun checkTargetPage(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("apiVersion", "generatedAt", "targets", "nextPageCursor", "syncCursor")); run { val p = o.getValue("apiVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("generatedAt") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val a = o.getValue("targets") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkConfirmedTarget(item) } }; run { val p = o.getValue("nextPageCursor") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("syncCursor") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) } } }
    fun checkTargetChange(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("sequence", "operation", "target")); run { val p = o.getValue("sequence") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("operation") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkConfirmedTarget(o.getValue("target")) } }
    fun checkSyncPage(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("apiVersion", "changes", "nextCursor", "hasMore")); run { val p = o.getValue("apiVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val a = o.getValue("changes") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkTargetChange(item) } }; run { val p = o.getValue("nextCursor") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("hasMore") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.booleanOrNull != null) } } }
}
