// Generated by contracts/scripts/generate.mjs v1. Do not edit.
package com.germanverbmaster.android.foundation.contract

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.*

@Serializable
data class Option(
    val id: String,
    val text: String
) {
    init {
        require(id.length >= 1) { "Invalid Option.id" }
        require(text.length >= 1) { "Invalid Option.text" }
    }
}

@Serializable
data class Slot(
    val id: String,
    val label: String
) {
    init {
        require(id.length >= 1) { "Invalid Slot.id" }
        require(label.length >= 1) { "Invalid Slot.label" }
    }
}

@Serializable
data class SlotValue(
    val slotId: String,
    val text: String
) {
    init {
        require(slotId.length >= 1) { "Invalid SlotValue.slotId" }
    }
}

@Serializable
data class LocalizedText(
    val en: String,
    val de: String
) {
    init {
        require(en.length >= 1) { "Invalid LocalizedText.en" }
        require(de.length >= 1) { "Invalid LocalizedText.de" }
    }
}

@Serializable
@SerialName("short_answer")
data class ExerciseShortAnswer(
    override val schemaVersion: Int,
    override val id: String,
    override val revision: Int,
    override val targetId: String,
    override val prompt: String,
    override val instruction: LocalizedText,
    override val hint: LocalizedText
) : Exercise() {
    init {
        require(schemaVersion == 1) { "Invalid ExerciseShortAnswer.schemaVersion" }
        require(schemaVersion <= 2147483647) { "Invalid ExerciseShortAnswer.schemaVersion" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(id)) { "Invalid ExerciseShortAnswer.id" }
        require(revision >= 1) { "Invalid ExerciseShortAnswer.revision" }
        require(revision <= 2147483647) { "Invalid ExerciseShortAnswer.revision" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(targetId)) { "Invalid ExerciseShortAnswer.targetId" }
        require(prompt.length >= 1) { "Invalid ExerciseShortAnswer.prompt" }
    }
}

@Serializable
@SerialName("choice")
data class ExerciseChoice(
    override val schemaVersion: Int,
    override val id: String,
    override val revision: Int,
    override val targetId: String,
    override val prompt: String,
    override val instruction: LocalizedText,
    override val hint: LocalizedText,
    val options: List<Option>
) : Exercise() {
    init {
        require(schemaVersion == 1) { "Invalid ExerciseChoice.schemaVersion" }
        require(schemaVersion <= 2147483647) { "Invalid ExerciseChoice.schemaVersion" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(id)) { "Invalid ExerciseChoice.id" }
        require(revision >= 1) { "Invalid ExerciseChoice.revision" }
        require(revision <= 2147483647) { "Invalid ExerciseChoice.revision" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(targetId)) { "Invalid ExerciseChoice.targetId" }
        require(prompt.length >= 1) { "Invalid ExerciseChoice.prompt" }
        require(options.size >= 2) { "Invalid ExerciseChoice.options" }
    }
}

@Serializable
@SerialName("cloze")
data class ExerciseCloze(
    override val schemaVersion: Int,
    override val id: String,
    override val revision: Int,
    override val targetId: String,
    override val prompt: String,
    override val instruction: LocalizedText,
    override val hint: LocalizedText,
    val slots: List<Slot>
) : Exercise() {
    init {
        require(schemaVersion == 1) { "Invalid ExerciseCloze.schemaVersion" }
        require(schemaVersion <= 2147483647) { "Invalid ExerciseCloze.schemaVersion" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(id)) { "Invalid ExerciseCloze.id" }
        require(revision >= 1) { "Invalid ExerciseCloze.revision" }
        require(revision <= 2147483647) { "Invalid ExerciseCloze.revision" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(targetId)) { "Invalid ExerciseCloze.targetId" }
        require(prompt.length >= 1) { "Invalid ExerciseCloze.prompt" }
        require(slots.size >= 1) { "Invalid ExerciseCloze.slots" }
    }
}

@Serializable
@SerialName("word_order")
data class ExerciseWordOrder(
    override val schemaVersion: Int,
    override val id: String,
    override val revision: Int,
    override val targetId: String,
    override val prompt: String,
    override val instruction: LocalizedText,
    override val hint: LocalizedText,
    val tokens: List<Option>
) : Exercise() {
    init {
        require(schemaVersion == 1) { "Invalid ExerciseWordOrder.schemaVersion" }
        require(schemaVersion <= 2147483647) { "Invalid ExerciseWordOrder.schemaVersion" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(id)) { "Invalid ExerciseWordOrder.id" }
        require(revision >= 1) { "Invalid ExerciseWordOrder.revision" }
        require(revision <= 2147483647) { "Invalid ExerciseWordOrder.revision" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(targetId)) { "Invalid ExerciseWordOrder.targetId" }
        require(prompt.length >= 1) { "Invalid ExerciseWordOrder.prompt" }
        require(tokens.size >= 2) { "Invalid ExerciseWordOrder.tokens" }
    }
}

@Serializable
@SerialName("multi_slot")
data class ExerciseMultiSlot(
    override val schemaVersion: Int,
    override val id: String,
    override val revision: Int,
    override val targetId: String,
    override val prompt: String,
    override val instruction: LocalizedText,
    override val hint: LocalizedText,
    val slots: List<Slot>
) : Exercise() {
    init {
        require(schemaVersion == 1) { "Invalid ExerciseMultiSlot.schemaVersion" }
        require(schemaVersion <= 2147483647) { "Invalid ExerciseMultiSlot.schemaVersion" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(id)) { "Invalid ExerciseMultiSlot.id" }
        require(revision >= 1) { "Invalid ExerciseMultiSlot.revision" }
        require(revision <= 2147483647) { "Invalid ExerciseMultiSlot.revision" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(targetId)) { "Invalid ExerciseMultiSlot.targetId" }
        require(prompt.length >= 1) { "Invalid ExerciseMultiSlot.prompt" }
        require(slots.size >= 2) { "Invalid ExerciseMultiSlot.slots" }
    }
}

@Serializable
@SerialName("short_answer")
data class AnswerShortAnswer(
    val text: String
) : Answer() {
    init {

    }
}

@Serializable
@SerialName("choice")
data class AnswerChoice(
    val optionId: String
) : Answer() {
    init {
        require(optionId.length >= 1) { "Invalid AnswerChoice.optionId" }
    }
}

@Serializable
@SerialName("cloze")
data class AnswerCloze(
    val values: List<SlotValue>
) : Answer() {
    init {
        require(values.size >= 1) { "Invalid AnswerCloze.values" }
    }
}

@Serializable
@SerialName("word_order")
data class AnswerWordOrder(
    val tokenIds: List<String>
) : Answer() {
    init {
        require(tokenIds.size >= 2) { "Invalid AnswerWordOrder.tokenIds" }
        require(tokenIds.distinct().size == tokenIds.size) { "Invalid AnswerWordOrder.tokenIds" }
        require(tokenIds.all { it.length >= 1 }) { "Invalid AnswerWordOrder.tokenIds" }
    }
}

@Serializable
@SerialName("multi_slot")
data class AnswerMultiSlot(
    val values: List<SlotValue>
) : Answer() {
    init {
        require(values.size >= 2) { "Invalid AnswerMultiSlot.values" }
    }
}

@Serializable
@OptIn(kotlinx.serialization.ExperimentalSerializationApi::class)
@JsonClassDiscriminator("type")
sealed class Exercise {
    abstract val schemaVersion: Int
    abstract val id: String
    abstract val revision: Int
    abstract val targetId: String
    abstract val prompt: String
    abstract val instruction: LocalizedText
    abstract val hint: LocalizedText
}

@Serializable
@OptIn(kotlinx.serialization.ExperimentalSerializationApi::class)
@JsonClassDiscriminator("type")
sealed class Answer {

}

@Serializable
data class Question(
    val id: String,
    val exercise: Exercise
) {
    init {
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(id)) { "Invalid Question.id" }
    }
}

@Serializable
data class Session(
    val apiVersion: String,
    val id: String,
    val contentReleaseId: String,
    val questions: List<Question>
) {
    init {
        require(apiVersion == "v2") { "Invalid Session.apiVersion" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(id)) { "Invalid Session.id" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(contentReleaseId)) { "Invalid Session.contentReleaseId" }
        require(questions.size >= 1) { "Invalid Session.questions" }
        require(questions.size <= 50) { "Invalid Session.questions" }
    }
}

@Serializable
data class Attempt(
    val attemptId: String,
    val sessionQuestionId: String,
    val exerciseRevision: Int,
    val deviceId: String,
    val answer: Answer,
    val assistance: List<String>,
    val answeredAt: String,
    val clientSequence: Int
) {
    init {
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(attemptId)) { "Invalid Attempt.attemptId" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(sessionQuestionId)) { "Invalid Attempt.sessionQuestionId" }
        require(exerciseRevision >= 1) { "Invalid Attempt.exerciseRevision" }
        require(exerciseRevision <= 2147483647) { "Invalid Attempt.exerciseRevision" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(deviceId)) { "Invalid Attempt.deviceId" }
        require(assistance.all { it in setOf("hint", "reveal") }) { "Invalid Attempt.assistance" }
        require(Regex("^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$").matches(answeredAt)) { "Invalid Attempt.answeredAt" }
        require(runCatching { java.time.Instant.parse(answeredAt).toString() == answeredAt }.getOrDefault(false)) { "Invalid Attempt.answeredAt" }
        require(clientSequence >= 0) { "Invalid Attempt.clientSequence" }
        require(clientSequence <= 2147483647) { "Invalid Attempt.clientSequence" }
    }
}

@Serializable
data class AttemptBatch(
    val apiVersion: String,
    val attempts: List<Attempt>
) {
    init {
        require(apiVersion == "v2") { "Invalid AttemptBatch.apiVersion" }
        require(attempts.size >= 1) { "Invalid AttemptBatch.attempts" }
        require(attempts.size <= 50) { "Invalid AttemptBatch.attempts" }
    }
}

@Serializable
data class ApiError(
    val code: String,
    val message: String,
    val requestId: String,
    val retryable: Boolean
) {
    init {
        require(code.length >= 1) { "Invalid ApiError.code" }
        require(message.length >= 1) { "Invalid ApiError.message" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(requestId)) { "Invalid ApiError.requestId" }
    }
}

@Serializable
data class SessionRequest(
    val apiVersion: String,
    val requestId: String,
    val questionCount: Int,
    val capabilities: List<String>
) {
    init {
        require(apiVersion == "v2") { "Invalid SessionRequest.apiVersion" }
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(requestId)) { "Invalid SessionRequest.requestId" }
        require(questionCount >= 1) { "Invalid SessionRequest.questionCount" }
        require(questionCount <= 50) { "Invalid SessionRequest.questionCount" }
        require(capabilities.size >= 1) { "Invalid SessionRequest.capabilities" }
        require(capabilities.distinct().size == capabilities.size) { "Invalid SessionRequest.capabilities" }
        require(capabilities.all { it in setOf("short_answer@1", "choice@1", "cloze@1", "word_order@1", "multi_slot@1") }) { "Invalid SessionRequest.capabilities" }
    }
}

@Serializable
data class Evaluation(
    val outcome: String,
    val policyVersion: String,
    val explanation: LocalizedText,
    val acceptedAnswer: Answer,
    val assisted: Boolean
) {
    init {
        require(outcome in setOf("correct", "incorrect", "skipped")) { "Invalid Evaluation.outcome" }
        require(policyVersion.length >= 1) { "Invalid Evaluation.policyVersion" }
    }
}

@Serializable
@SerialName("accepted")
data class AttemptAcknowledgment(
    override val attemptId: String,
    val evaluation: Evaluation,
    val serverSequence: Int
) : Acknowledgment() {
    init {
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(attemptId)) { "Invalid AttemptAcknowledgment.attemptId" }
        require(serverSequence >= 0) { "Invalid AttemptAcknowledgment.serverSequence" }
        require(serverSequence <= 2147483647) { "Invalid AttemptAcknowledgment.serverSequence" }
    }
}

@Serializable
@SerialName("rejected")
data class AttemptRejection(
    override val attemptId: String,
    val error: ApiError
) : Acknowledgment() {
    init {
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(attemptId)) { "Invalid AttemptRejection.attemptId" }
    }
}

@Serializable
@SerialName("duplicate")
data class AttemptDuplicate(
    override val attemptId: String,
    val evaluation: Evaluation,
    val serverSequence: Int
) : Acknowledgment() {
    init {
        require(Regex("^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$").matches(attemptId)) { "Invalid AttemptDuplicate.attemptId" }
        require(serverSequence >= 0) { "Invalid AttemptDuplicate.serverSequence" }
        require(serverSequence <= 2147483647) { "Invalid AttemptDuplicate.serverSequence" }
    }
}

@Serializable
@OptIn(kotlinx.serialization.ExperimentalSerializationApi::class)
@JsonClassDiscriminator("status")
sealed class Acknowledgment {
    abstract val attemptId: String
}

@Serializable
data class AttemptBatchResponse(
    val apiVersion: String,
    val acknowledgments: List<Acknowledgment>
) {
    init {
        require(apiVersion == "v2") { "Invalid AttemptBatchResponse.apiVersion" }
        require(acknowledgments.size >= 1) { "Invalid AttemptBatchResponse.acknowledgments" }
        require(acknowledgments.size <= 50) { "Invalid AttemptBatchResponse.acknowledgments" }
    }
}

object ContractShape {
    fun checkOption(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("id", "text")); run { val p = o.getValue("id") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("text") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) } } }
    fun checkSlot(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("id", "label")); run { val p = o.getValue("id") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("label") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) } } }
    fun checkSlotValue(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("slotId", "text")); run { val p = o.getValue("slotId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("text") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) } } }
    fun checkLocalizedText(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("en", "de")); run { val p = o.getValue("en") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("de") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) } } }
    fun checkExerciseShortAnswer(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("type", "schemaVersion", "id", "revision", "targetId", "prompt", "instruction", "hint")); run { val p = o.getValue("type") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("schemaVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("id") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("revision") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("targetId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("prompt") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkLocalizedText(o.getValue("instruction")); checkLocalizedText(o.getValue("hint")) } }
    fun checkExerciseChoice(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("type", "schemaVersion", "id", "revision", "targetId", "prompt", "instruction", "hint", "options")); run { val p = o.getValue("type") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("schemaVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("id") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("revision") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("targetId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("prompt") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkLocalizedText(o.getValue("instruction")); checkLocalizedText(o.getValue("hint")); run { val a = o.getValue("options") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkOption(item) } } } }
    fun checkExerciseCloze(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("type", "schemaVersion", "id", "revision", "targetId", "prompt", "instruction", "hint", "slots")); run { val p = o.getValue("type") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("schemaVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("id") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("revision") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("targetId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("prompt") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkLocalizedText(o.getValue("instruction")); checkLocalizedText(o.getValue("hint")); run { val a = o.getValue("slots") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkSlot(item) } } } }
    fun checkExerciseWordOrder(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("type", "schemaVersion", "id", "revision", "targetId", "prompt", "instruction", "hint", "tokens")); run { val p = o.getValue("type") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("schemaVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("id") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("revision") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("targetId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("prompt") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkLocalizedText(o.getValue("instruction")); checkLocalizedText(o.getValue("hint")); run { val a = o.getValue("tokens") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkOption(item) } } } }
    fun checkExerciseMultiSlot(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("type", "schemaVersion", "id", "revision", "targetId", "prompt", "instruction", "hint", "slots")); run { val p = o.getValue("type") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("schemaVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("id") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("revision") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("targetId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("prompt") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkLocalizedText(o.getValue("instruction")); checkLocalizedText(o.getValue("hint")); run { val a = o.getValue("slots") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkSlot(item) } } } }
    fun checkAnswerShortAnswer(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("type", "text")); run { val p = o.getValue("type") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("text") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) } } }
    fun checkAnswerChoice(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("type", "optionId")); run { val p = o.getValue("type") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("optionId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) } } }
    fun checkAnswerCloze(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("type", "values")); run { val p = o.getValue("type") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val a = o.getValue("values") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkSlotValue(item) } } } }
    fun checkAnswerWordOrder(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("type", "tokenIds")); run { val p = o.getValue("type") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val a = o.getValue("tokenIds") as? JsonArray ?: error("Expected array"); a.forEach { item -> run { val p = item as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) } } } } }
    fun checkAnswerMultiSlot(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("type", "values")); run { val p = o.getValue("type") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val a = o.getValue("values") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkSlotValue(item) } } } }
    fun checkExercise(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); val tag=o["type"] as? JsonPrimitive ?: error("Missing discriminator"); require(tag.isString); when(tag.content) { "short_answer" -> checkExerciseShortAnswer(element); "choice" -> checkExerciseChoice(element); "cloze" -> checkExerciseCloze(element); "word_order" -> checkExerciseWordOrder(element); "multi_slot" -> checkExerciseMultiSlot(element); else -> error("Unsupported discriminator") } } }
    fun checkAnswer(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); val tag=o["type"] as? JsonPrimitive ?: error("Missing discriminator"); require(tag.isString); when(tag.content) { "short_answer" -> checkAnswerShortAnswer(element); "choice" -> checkAnswerChoice(element); "cloze" -> checkAnswerCloze(element); "word_order" -> checkAnswerWordOrder(element); "multi_slot" -> checkAnswerMultiSlot(element); else -> error("Unsupported discriminator") } } }
    fun checkQuestion(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("id", "exercise")); run { val p = o.getValue("id") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkExercise(o.getValue("exercise")) } }
    fun checkSession(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("apiVersion", "id", "contentReleaseId", "questions")); run { val p = o.getValue("apiVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("id") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("contentReleaseId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val a = o.getValue("questions") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkQuestion(item) } } } }
    fun checkAttempt(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("attemptId", "sessionQuestionId", "exerciseRevision", "deviceId", "answer", "assistance", "answeredAt", "clientSequence")); run { val p = o.getValue("attemptId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("sessionQuestionId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("exerciseRevision") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val p = o.getValue("deviceId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkAnswer(o.getValue("answer")); run { val a = o.getValue("assistance") as? JsonArray ?: error("Expected array"); a.forEach { item -> run { val p = item as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) } } }; run { val p = o.getValue("answeredAt") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("clientSequence") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) } } }
    fun checkAttemptBatch(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("apiVersion", "attempts")); run { val p = o.getValue("apiVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val a = o.getValue("attempts") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkAttempt(item) } } } }
    fun checkApiError(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("code", "message", "requestId", "retryable")); run { val p = o.getValue("code") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("message") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("requestId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("retryable") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.booleanOrNull != null) } } }
    fun checkSessionRequest(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("apiVersion", "requestId", "questionCount", "capabilities")); run { val p = o.getValue("apiVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("requestId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("questionCount") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) }; run { val a = o.getValue("capabilities") as? JsonArray ?: error("Expected array"); a.forEach { item -> run { val p = item as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) } } } } }
    fun checkEvaluation(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("outcome", "policyVersion", "explanation", "acceptedAnswer", "assisted")); run { val p = o.getValue("outcome") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("policyVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkLocalizedText(o.getValue("explanation")); checkAnswer(o.getValue("acceptedAnswer")); run { val p = o.getValue("assisted") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.booleanOrNull != null) } } }
    fun checkAttemptAcknowledgment(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("attemptId", "status", "evaluation", "serverSequence")); run { val p = o.getValue("attemptId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("status") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkEvaluation(o.getValue("evaluation")); run { val p = o.getValue("serverSequence") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) } } }
    fun checkAttemptRejection(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("attemptId", "status", "error")); run { val p = o.getValue("attemptId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("status") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkApiError(o.getValue("error")) } }
    fun checkAttemptDuplicate(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("attemptId", "status", "evaluation", "serverSequence")); run { val p = o.getValue("attemptId") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val p = o.getValue("status") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; checkEvaluation(o.getValue("evaluation")); run { val p = o.getValue("serverSequence") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && !p.isString && p.intOrNull != null) } } }
    fun checkAcknowledgment(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); val tag=o["status"] as? JsonPrimitive ?: error("Missing discriminator"); require(tag.isString); when(tag.content) { "accepted" -> checkAttemptAcknowledgment(element); "duplicate" -> checkAttemptDuplicate(element); "rejected" -> checkAttemptRejection(element); else -> error("Unsupported discriminator") } } }
    fun checkAttemptBatchResponse(element: JsonElement): Unit { run { val o = element as? JsonObject ?: error("Expected object"); require(o.keys == setOf("apiVersion", "acknowledgments")); run { val p = o.getValue("apiVersion") as? JsonPrimitive ?: error("Expected primitive"); require(p !is JsonNull && p.isString) }; run { val a = o.getValue("acknowledgments") as? JsonArray ?: error("Expected array"); a.forEach { item -> checkAcknowledgment(item) } } } }
}
