import { beforeAll, afterAll, it, expect } from 'vitest';
import { PGlite } from '@electric-sql/pglite';
import { randomUUID } from 'node:crypto';
import { LearnerExportSchema, PrivacyDeleteReceiptSchema } from '@german-master/contracts';
import { FoundationStore } from './store';
import { createApi } from './server';
import answers from '../../../contracts/v2/examples/attempt-batch.json';
let db:PGlite, store:FoundationStore, server:ReturnType<typeof createApi>, base:string;
const user=randomUUID(), other=randomUUID();
const headers={Authorization:'Bearer fixture','Content-Type':'application/json','X-Learner-Subject':user};
const request={apiVersion:'v2' as const,requestId:randomUUID(),confirmation:'delete_owned_data' as const};
const sessionRequest=()=>({apiVersion:'v2' as const,requestId:randomUUID(),questionCount:1,capabilities:['short_answer@1' as const]});
let frozen:Parameters<FoundationStore['submit']>[1];
beforeAll(async()=>{
  db=new PGlite();store=new FoundationStore(db);await store.initialize();
  server=createApi(store,async r=>r.headers.authorization==='Bearer fixture'?user:null);
  await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));
  base=`http://127.0.0.1:${(server.address() as {port:number}).port}`;
});
afterAll(async()=>{await new Promise<void>(resolve=>server.close(()=>resolve()));await db.close();});
it('exports only owned confirmed data with versioned schemas and no cached response',async()=>{
  await store.createSession(other,sessionRequest());
  await store.saveProfile(user,{apiVersion:'v2',requestId:randomUUID(),expectedRevision:0,preferences:{locale:'de',timezone:'UTC',level:'B1',sessionQuestionCount:5}});
  const session=await store.createSession(user,sessionRequest());
  frozen={...answers.attempts[0],attemptId:randomUUID(),sessionQuestionId:session.questions[0].id,answer:{type:'short_answer',text:'Berufe'},assistance:[]};
  expect((await store.submit(user,frozen,randomUUID())).status).toBe('accepted');
  await store.report(user,{apiVersion:'v2',reportId:randomUUID(),sessionQuestionId:session.questions[0].id,exerciseRevision:session.questions[0].exercise.revision,category:'other'});
  await store.complete(user,session.id,{apiVersion:'v2',requestId:randomUUID(),mode:'full'});
  await store.preparePack(user,sessionRequest());
  await store.targets(user);await store.sync(user);
  expect((await fetch(base+'/v2/me/export')).status).toBe(401);
  expect((await fetch(base+'/v2/me/export?subject='+other,{headers})).status).toBe(400);
  expect((await fetch(base+'/v2/me/export',{headers:{...headers,'X-Learner-Subject':other}})).status).toBe(409);
  const response=await fetch(base+'/v2/me/export',{headers});expect(response.headers.get('cache-control')).toBe('no-store');
  const data=LearnerExportSchema.parse(await response.json());
  expect(data.subject).toBe(user);expect(data.profile.preferences.locale).toBe('de');
  expect(data.attempts).toEqual([frozen]);expect(data.evaluations).toHaveLength(1);expect(data.targets).toHaveLength(1);
  expect(data.reports).toHaveLength(1);expect(data.completions).toHaveLength(1);
  expect(data.sessions.every(s=>s.id!==other)).toBe(true);
  expect((await store.exportLearner(other)).attempts).toEqual([]);
});
it('deletes owned data atomically, replays a lost response and refuses abandoned writes after reinitialization',async()=>{
  const invalid=await fetch(base+'/v2/me',{method:'DELETE',headers,body:JSON.stringify({...request,subject:other})});expect(invalid.status).toBe(400);
  const otherBefore=await store.exportLearner(other);
  const before=await store.exportLearner(user);
  await db.exec('CREATE TRIGGER fail_privacy_delete BEFORE DELETE ON gm.learner_profile FOR EACH ROW EXECUTE FUNCTION gm.reject_mutation()');
  await expect(store.deleteLearner(user,request)).rejects.toThrow();
  expect({...await store.exportLearner(user),generatedAt:before.generatedAt}).toEqual(before);
  expect((await db.query('SELECT * FROM gm.deleted_learner WHERE user_id=$1',[user])).rows).toEqual([]);
  await db.exec('DROP TRIGGER fail_privacy_delete ON gm.learner_profile');
  const response=await fetch(base+'/v2/me',{method:'DELETE',headers,body:JSON.stringify(request)});
  expect(response.status).toBe(200);const receipt=PrivacyDeleteReceiptSchema.parse(await response.json());
  await store.initialize();
  expect(await store.deleteLearner(user,request)).toEqual(receipt);
  await expect(store.deleteLearner(user,{...request,requestId:randomUUID()})).rejects.toMatchObject({code:'deletion_conflict'});
  expect((await fetch(base+'/v2/me/export',{headers})).status).toBe(410);
  await expect(store.createSession(user,sessionRequest())).rejects.toMatchObject({code:'account_deleted'});
  await expect(store.profile(user)).rejects.toMatchObject({code:'account_deleted'});
  expect(await store.submit(user,frozen,randomUUID())).toMatchObject({status:'rejected',error:{code:'account_deleted',retryable:false}});
  expect({...await store.exportLearner(other),generatedAt:otherBefore.generatedAt}).toEqual(otherBefore);
  const tables=await db.query<{table_name:string}>("SELECT table_name FROM information_schema.columns WHERE table_schema='gm' AND column_name='user_id' AND table_name<>'deleted_learner'");
  for(const {table_name} of tables.rows) expect((await db.query(`SELECT * FROM gm.${table_name} WHERE user_id=$1`,[user])).rows).toEqual([]);
  expect((await db.query('SELECT * FROM gm.exercise_revision')).rows).toHaveLength(5);
  await expect(db.query('DELETE FROM gm.practice_session WHERE user_id=$1',[other])).rejects.toThrow('immutable');
});
